### PR TITLE
Fix python3 types and PAC module

### LINKED ISSUE #23: Rewrite error
when i try Rewrite
image
image

what happend?

### PR DESCRIPTION
**Pull request by blitztide**
resolves #23

### CODE REVIEW

**Review by nidem — APPROVED** [review]

**Review by invisiblepancake — COMMENTED** [review]
String to Byte Conversion:
        return '\xff\xff\xff\xff\xff\xff\xff\x7f' was changed to return b'\xff\xff\xff\xff\xff\xff\xff\x7f'
        return s + '\x00' * ((alignment - (len(s) % alignment)) % alignment) was changed to handle both string and byte types.

    Encode and Decode Methods:
        .encode('hex') was updated to .hex()
        .decode('hex') was updated to bytearray.fromhex(a)

    String Handling:
        chr(messagetype) + "\x00\x00\x00" was changed to bytes(messagetype) + b'\x00\x00\x00'
        list(map(ord, data)) was updated to list(map(ord, str(data)))
        The string concatenations involving '\x00\x00\x00\x00' were changed to b'\x00\x00\x00\x00'

    Struct Packing:
        struct.pack('<LLL', len(self.AccountName)/2, 0, len(self.AccountName)/2) was changed to use int(len(self.AccountName)/2) to ensure integer division.

    Generalized Time Conversion:
        ticket.getComponentByPosition(5)._value = useful.GeneralizedTime(authtime) was changed to ticket.getComponentByPosition(5)._value = str(useful.GeneralizedTime(authtime))

    Checksum Calculation:
        kerberos.chksum(key, '\x11\x00\x00\x00', pac) was changed to kerberos.chksum(key, b'\x11\x00\x00\x00', pac)

    Miscellaneous:
        TGS_REP = chr(13) was changed to TGS_REP = 13
        args.outfile.write(p.encode('hex') + '\n') was changed to args.outfile.write(p.hex() + '\n')

These changes ensure compatibility with Python 3, which differentiates between strings (text) and bytes (binary data).

**Review by invisiblepancake — COMMENTED** [review]
File: extracttgsrepfrompcap.py
Line 10: Changed TGS_REP = chr(13) to TGS_REP = 13.
Line 80: Replaced p.encode('hex') with p.hex().
File: kerberoast.py
Line 41-44: Converted GeneralizedTime objects to strings using str().
Line 108: Changed pac = str(adifrelevant.getComponentByPosition(0).getComponentByPosition(1)) to pac = adifrelevant.getComponentByPosition(0).getComponentByPosition(1).
Line 110: Changed return pac to return bytearray(pac).
Line 147: Changed kerberos.chksum(key, '\x11\x00\x00\x00', pac) to kerberos.chksum(key, b'\x11\x00\x00\x00', pac).
Line 224-225: Changed pac = getpac(key, fullraw) to pac_str = getpac(key, fullraw) and pacobj = PAC.PAC(pac) to pacobj = pac.PAC(pac=pac_str).
Line 242-243: Changed pac = pacobj.encode() to pac_str = pacobj.encode() and newticket = updatepac(key, fullraw, pac) to newticket = updatepac(key, fullraw, pac_str).
File: kerberos.py
Line 108: Changed hmac.new(key, chr(messagetype) + "\x00\x00\x00", hashlib.md5).digest() to hmac.new(key, bytes(messagetype) + b'\x00\x00\x00', hashlib.md5).digest().
Line 129: Changed list(map(ord, data)) to list(map(ord, str(data))).
Line 139: Changed return retval to return bytearray(retval,"utf-8").
Line 148: Changed SIGNATUREKEY = 'signaturekey\x00' to SIGNATUREKEY = b'signaturekey\x00'.
File: pac.py
Line 28: Changed return '\xff\xff\xff\xff\xff\xff\xff\x7f' to return b'\xff\xff\xff\xff\xff\xff\xff\x7f'.
Line 69-72: Added type checking for AlignedString function to handle both str and bytearray types.
Line 118: Changed self.Data.encode('hex') to self.Data.hex().
Line 315-319: Changed division results to integers in struct.pack calls.
Line 350: Changed self.Data[10:10+namelen].encode('utf-8') to self.Data[10:10+namelen].decode('utf-8').
Line 357: Changed struct.pack('<H', len(self.Name)) + self.Name to struct.pack('<H', len(self.Name)) + bytearray(self.Name,"utf-8").
Line 395: Changed str(AlignedString(self.UPNName)) to AlignedString(self.UPNName).
Line 411, 431: Changed self.SigVal.encode('hex') to self.SigVal.hex().
Line 518-522: Changed headers = '' and payload = '' to headers = b'' and payload = b''.
Line 577: Changed a.decode('hex') to bytearray.fromhex(a).
Line 579: Changed PAC(a) to PAC(pac=a).
Summary
The changes primarily focus on improving compatibility with Python 3 by replacing string manipulations that are specific to Python 2 (e.g., chr(), encode('hex')) with Python 3 compatible methods (e.g., bytes(), hex()).
The changes also handle byte and string conversions more explicitly, which is important for correct behavior in Python 3.

**Comment by nidem** [comment]
@invisiblepancake I don't see your pull request. I only see your comments on what should change.

**Comment by invisiblepancake** [comment]
@nidem Im taking an hold, whaiting for some hardware.  Next week i hope =)

**Pull request merged**
